const cars = [
  {
    id: 1,
    name: "Creta",
    brand: "Hyundai",
    price: "12 Lakh",
    engine: "1497 cc",
    power: "113 bhp",
    mileage: "17 kmpl",
    fuel: "Petrol",
    torque: "144 Nm",
    safety: "5 Star",
    seats: 5,
    image: "/cars/creta.jpg"
  },
  {
    id: 2,
    name: "Thar",
    brand: "Mahindra",
    price: "14 Lakh",
    engine: "2184 cc",
    power: "130 bhp",
    mileage: "15 kmpl",
    fuel: "Diesel",
    torque: "300 Nm",
    safety: "4 Star",
    seats: 4,
    image: "/cars/thar.jpg"
  },
  {
    id: 3,
    name: "Nexon",
    brand: "Tata",
    price: "9 Lakh",
    engine: "1497 cc",
    power: "118 bhp",
    mileage: "17 kmpl",
    fuel: "Petrol",
    torque: "260 Nm",
    safety: "5 Star",
    seats: 5,
    image: "/cars/nexon.jpg"
  },
  {
    id: 4,
    name: "Harrier",
    brand: "Tata",
    price: "15 Lakh",
    engine: "1956 cc",
    power: "167 bhp",
    mileage: "16 kmpl",
    fuel: "Diesel",
    torque: "350 Nm",
    safety: "5 Star",
    seats: 5,
    image: "/cars/harrier.jpg"
  },
  {
    id: 5,
    name: "Swift",
    brand: "Maruti",
    price: "6 Lakh",
    engine: "1197 cc",
    power: "89 bhp",
    mileage: "22 kmpl",
    fuel: "Petrol",
    torque: "113 Nm",
    safety: "2 Star",
    seats: 5,
    image: "/cars/swift.jpg"
  },
  {
    id: 6,
    name: "City",
    brand: "Honda",
    price: "11 Lakh",
    engine: "1498 cc",
    power: "119 bhp",
    mileage: "18 kmpl",
    fuel: "Petrol",
    torque: "145 Nm",
    safety: "5 Star",
    seats: 5,
    image: "/cars/city.jpg"
  },
  {
    id: 7,
    name: "Seltos",
    brand: "Kia",
    price: "11 Lakh",
    engine: "1497 cc",
    power: "113 bhp",
    mileage: "17 kmpl",
    fuel: "Petrol",
    torque: "144 Nm",
    safety: "3 Star",
    seats: 5,
    image: "/cars/seltos.jpg"
  },
  {
    id: 8,
    name: "Fortuner",
    brand: "Toyota",
    price: "33 Lakh",
    engine: "2755 cc",
    power: "201 bhp",
    mileage: "14 kmpl",
    fuel: "Diesel",
    torque: "420 Nm",
    safety: "5 Star",
    seats: 7,
    image: "/cars/fortuner.jpg"
  },
  {
    id: 9,
    name: "Verna",
    brand: "Hyundai",
    price: "10 Lakh",
    engine: "1497 cc",
    power: "113 bhp",
    mileage: "18 kmpl",
    fuel: "Petrol",
    torque: "143 Nm",
    safety: "5 Star",
    seats: 5,
    image: "/cars/verna.jpg"
  },
  {
    id: 10,
    name: "XUV700",
    brand: "Mahindra",
    price: "14 Lakh",
    engine: "1999 cc",
    power: "200 bhp",
    mileage: "15 kmpl",
    fuel: "Petrol",
    torque: "380 Nm",
    safety: "5 Star",
    seats: 7,
    image: "/cars/xuv700.jpg"
  }
];

export default cars;
